site_name: morethemes
site_url: https://josephbarbierdarnal.github.io/morethemes/
repo_url: https://github.com/JosephBARBIERDARNAL/morethemes
theme:
  name: material
  custom_dir: overrides
  features:
    - content.code.copy
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/style.css

extra:
  analytics:
    provider: google
    property: G-MXWMXGPX59

plugins:
  - mkdocs_matplotlib

nav:
  - Home: index.md
  - Contributing: contributing.md
  - Guide:
      - guide/reference.md
      - guide/custom-a-theme.md
      - guide/create-your-theme.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
